# Pandas Exercises

## Creating DataFrames and Using Sample Data Sets

This is the Jupyter Notebook runnable exercises version of the article, [Pandas Practice Questions – Fifty-Two Examples to Make You an Expert](https://codesolid.com/pandas-practice-questions-twenty-one-examples-to-make-you-an-expert/).

In [1]:
import pandas as pd
import numpy as np
import seaborn as sb

**1.** Using NumPy, create a Pandas DataFrame with five rows and three columms:

In [2]:
dff = pd.DataFrame(np.random.randint(0,100,size=(5, 3)), columns=list('ABC'))
dff

    A   B   C
0  84  46  53
1  59  68  13
2  35   9  82
3  29  57  86
4  77  68  87

**2.** For a Pandas DataFrame created from a NumPy array, what is the default behavior for the labels for the columns?  For the rows?

In [8]:
arr = np.random.randint(0,100,size=(5, 3))
df = pd.DataFrame(arr)
df

    0   1   2
0  86  66  18
1  51  80  24
2  76  34  20
3   8  21   2
4  57  50  47

**3.** Create a second DataFrame as above with five rows and three columns, setting the row labels to the names of any five major US cities and the column labels to the first three months of the year.

In [12]:
arr = np.random.randint(0, 100, size=(5,3))
df = pd.DataFrame(arr, index = ['New york', 'Houston', 'Los Angles', 'vegas', 'chicago'],
     columns=('January', 'February', 'March'))
df

            January  February  March
New york         88        22     55
Houston          65        30      9
Los Angles       93         8     62
vegas            45        30     72
chicago          30        41     55

**4.** You recall that the Seaborn package has some data sets built in, but can't remember how to list and load them. Assuming the functions to do so have "data" in the name, how might you locate them?  You can assume a Jupyter Notebook / IPython environment and explain the process, or write the code to do it in Python.

## Loading data from CSV

**5**. Zillow home data is available at this URL: https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv

Open this file as a DataFrame named df_homes in Pandas.

In [25]:
df_homes = pd.read_csv('https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv')
df_homes

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31,2026-08-31
0,102001,0,United States,country,NaN,123577.759599,123795.172495,124064.796497,124643.087057,125308.630160,...,365789.637187,366588.387076,367350.446884,368071.714278,368567.172902,368647.332960,368385.291351,368141.647036,368249.996720,368696.684749
1,394913,1,"New York, NY",msa,NY,220013.123643,220948.055283,221891.646074,223803.726142,225783.751268,...,708946.175873,712394.824490,715484.029453,719086.862434,722906.455133,725334.945516,726872.561905,728366.597785,731367.802254,735075.472720
2,753899,2,"Los Angeles, CA",msa,CA,221912.269808,222738.065012,223838.016347,226026.550004,228420.119716,...,948164.084432,952130.048187,954663.897072,955897.637375,955563.237098,953938.720216,952480.487123,950999.855511,951215.347307,952601.248169
3,394463,3,"Chicago, IL",msa,IL,156387.253909,156532.022949,156807.738135,157493.649000,158318.717268,...,344798.361117,346563.956713,348215.063279,349995.182297,351427.852617,352446.017678,353069.521399,353938.432884,355375.931563,357264.935404
4,394514,4,"Dallas, TX",msa,TX,129720.857830,129778.635953,129845.057821,130017.548434,130244.972584,...,367550.988498,367329.712410,366889.093929,366304.482462,365232.417762,363899.148350,362320.808555,361073.950589,360453.497967,360436.817305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,753929,935,"Zapata, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,129499.747262,129458.243561,130255.300687,131098.287406,132175.193979,131744.885980,130346.688002,127950.475247,126029.898165,124661.466121
891,394743,936,"Ketchikan, AK",msa,AK,NaN,NaN,NaN,NaN,NaN,...,387838.183554,389891.481435,391117.279530,391830.979067,393350.191648,395414.544594,397999.144736,400170.036280,401300.118963,401889.162523
892,753874,937,"Craig, CO",msa,CO,100782.547649,101040.255671,101520.040500,102203.298412,102997.290878,...,307232.762691,306721.058972,306872.631202,307586.954029,308504.320278,309168.812122,310115.243889,310375.496412,309867.986852,308449.251097
893,395188,938,"Vernon, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,104156.771330,105169.840586,105433.349827,105737.253365,105826.344027,106317.105261,106412.673020,106842.156093,107161.323354,107016.141762
894,394767,939,"Lamesa, TX",msa,TX,NaN,NaN,NaN,NaN,NaN,...,103697.373150,105936.398245,108505.359391,110699.992255,111191.244661,110582.117783,109138.203483,108240.172736,107776.205373,107805.614137

**6.** Save the DataFrame, df_homes, to a local CSV file, "zillow_home_data.csv".

In [20]:
#df.head(2)
df.to_csv('zillow_homw_data.csv')

 7. Load zillow_home_data.csv back into a new Dataframe, df_homes_2

In [22]:
import pandas as pd
df_homes_2 = pd.read_csv('zillow_homw_data.csv')
df_homes_2

,Unnamed: 0,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,...,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31,2026-08-31
0,0,102001,0,United States,country,NaN,123577.759599,123795.172495,124064.796497,124643.087057,...,365789.637187,366588.387076,367350.446884,368071.714278,368567.172902,368647.332960,368385.291351,368141.647036,368249.996720,368696.684749
1,1,394913,1,"New York, NY",msa,NY,220013.123643,220948.055283,221891.646074,223803.726142,...,708946.175873,712394.824490,715484.029453,719086.862434,722906.455133,725334.945516,726872.561905,728366.597785,731367.802254,735075.472720
2,2,753899,2,"Los Angeles, CA",msa,CA,221912.269808,222738.065012,223838.016347,226026.550004,...,948164.084432,952130.048187,954663.897072,955897.637375,955563.237098,953938.720216,952480.487123,950999.855511,951215.347307,952601.248169
3,3,394463,3,"Chicago, IL",msa,IL,156387.253909,156532.022949,156807.738135,157493.649000,...,344798.361117,346563.956713,348215.063279,349995.182297,351427.852617,352446.017678,353069.521399,353938.432884,355375.931563,357264.935404
4,4,394514,4,"Dallas, TX",msa,TX,129720.857830,129778.635953,129845.057821,130017.548434,...,367550.988498,367329.712410,366889.093929,366304.482462,365232.417762,363899.148350,362320.808555,361073.950589,360453.497967,360436.817305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,890,753929,935,"Zapata, TX",msa,TX,NaN,NaN,NaN,NaN,...,129499.747262,129458.243561,130255.300687,131098.287406,132175.193979,131744.885980,130346.688002,127950.475247,126029.898165,124661.466121
891,891,394743,936,"Ketchikan, AK",msa,AK,NaN,NaN,NaN,NaN,...,387838.183554,389891.481435,391117.279530,391830.979067,393350.191648,395414.544594,397999.144736,400170.036280,401300.118963,401889.162523
892,892,753874,937,"Craig, CO",msa,CO,100782.547649,101040.255671,101520.040500,102203.298412,...,307232.762691,306721.058972,306872.631202,307586.954029,308504.320278,309168.812122,310115.243889,310375.496412,309867.986852,308449.251097
893,893,395188,938,"Vernon, TX",msa,TX,NaN,NaN,NaN,NaN,...,104156.771330,105169.840586,105433.349827,105737.253365,105826.344027,106317.105261,106412.673020,106842.156093,107161.323354,107016.141762
894,894,394767,939,"Lamesa, TX",msa,TX,NaN,NaN,NaN,NaN,...,103697.373150,105936.398245,108505.359391,110699.992255,111191.244661,110582.117783,109138.203483,108240.172736,107776.205373,107805.614137

**8.** Compare the dimensions of the two DataFrames, df_homes and df_homes_2.  Are they equal?  If not, how can you fix it?

In [34]:
# df_homes.shape
# df_homes_2.shape

df_homes.shape == df_homes_2.shape

False

**9.** A remote spreadsheet showing how a snapshot of how traffic increased for a hypothetical website is available here: https://github.com/CodeSolid/CodeSolid.github.io/raw/main/booksource/data/AnalyticsSnapshot.xlsx. Load the worksheet page of the spreasheet data labelled "February 2022" as a DataFrame named "feb".  Note: the leftmost column in the spreadsheet is the index column.

**10.** The "Month to Month Increase" column is a bit hard to understand, so ignore it for now.  Given the values for "This Month" and "Last Month", create a new column, "Percentage Increase".

## Basic Operations on Data

**11.** Using Seaborn, get a dataset about penguins into a dataframe named "df_penguins".  Note that because all of the following questions depend on this example, we'll provide the solution here so no one gets stuck:

In [ ]:
df_penguins = sb.load_dataset('penguins')

**12.** Write the code to show the the number of rows and columns in df_penguins

**13.** How might you show the first few rows of df_penguins?

**14.** How can you return the unique species of penguins from df_penguins?  How many unique species are there?

**15.** What function can we use to drop the rows that have missing data?

**16.** By default, will this modify df_penguins or will it return a copy?

**17.** How can we override the default?

**18.** Create a new DataFrame, df_penguins_full, with the missing data deleted.

**19.** What is the average bill length of a penguin, in millimeters, in this (df_full) data set?

**20.** Which of the following is most strongly correlated with bill length?  a) Body mass?  b) Flipper length?  c) Bill depth?  Show how you arrived at the answer.

**21.** How could you show the median flipper length, grouped by species?

**22.** Which species has the longest flippers?

**23.** Which two species have the most similar mean weight?  Show how you arrived at the answer.

**24.** How could you sort the rows by bill length?

**25.** How could you run the same sort in descending order?

**26.** How could you sort by species first, then by body mass?

## Selecting Rows, Columns, and Cells

Let's look at some precious stones now, and leave the poor penguins alone for a while.  Let's look at some precious stones now, and leave the poor penguins alone for a while.

**27.** Load the Seaborn "diamonds" dataset into a Pandas dataframe named diamonds.

**28.** Display the columns that are available.

**29.** If you select a single column from the diamonds DataFrame, what will be the type of the return value?

**30.** Select the 'table' column and show its type

**31.** Select the first ten rows of the price and carat columns ten rows of the diamonds DataFrame into a variable called subset, and display them.

**32.** For a given column, show the code to display the datatype of the _values_ in the column?

**33.** Select the first row of the diamonds DataFrame into a variable called row.

**34.** What would you expect the data type of the row to be?  Display it.

A Pandas series

**35.** Can you discover the names of the columns using only the row returned in #33?  Why or why not?Can you discover the names of the columns using only the row returned in #33?  Why or why not?

Yes, because a row series should have the columns as the index (See below):

**36.** Select the row with the highest priced diamond.

**37.** Select the row with the lowest priced diamond.

## Some Exercises Using Time Series

**38.** Load the taxis dataset into a DataFrame, ```taxis```.

**39.** The 'pickup' column contains the date and time the customer picked up, but it's a string.  Add a column to the DataFrame, 'pickup_time', containing the value in 'pickup' as a DateTime.

**40.** We have a hypothesis that as the day goes on, the tips get higher.  We'll need to wrangle the data a bit before testing this, however.  First, now that we have a datetime column, pickup_time, create a subset of it to create a new DataFrame, taxis_one_day. This new DataFrame should have values between '2019-03-23 00:06:00' (inclusive) and '2019-03-24 00:00:00' (exlusive).

**41.** We now have a range from morning until midnight, but we to take the mean of the numeric columns, grouped at one hour intervals.  Save the result as df_means, and display it.

**42.** Create a simple line plot of the value "distance".

**43.** Overall, do riders travel further or less far as the day progresses?

**44.** Create a new column in taxis_means, ```tip_in_percent```.  The source columns for this should be "fare" and "tip"

**45.** Create a new column, time_interval, as a range of integer values beginning with zero.

Display the correlations between the following pairs of values:
1. tip_in_percent and distance.
1. tip_in_percent and passengers.
1. tip_in_percent and time_interval.

**47.** Admittedly, the size of the data set is fairly small given how we've subsetted it.  But based on the values in #45, which of the three pairs show the strongest correlation.

**48.** Did our hypothesis that people tip more as the day goes on turn out to be warranted?